import uuid
from datetime import datetime

from sqlalchemy import (String, Integer, DateTime, LargeBinary, CheckConstraint,
                        ForeignKey, ForeignKeyConstraint, Index, text)
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class OutboxEvent(Base):
    """A committed intention to send mail (0013).

    Written in the same transaction as the invitation it refers to, so the two
    are atomic together; delivered afterwards by outbox.dispatch_pending().

    Declared here and registered in app/models/__init__.py because a table
    missing from Base.metadata shows up in `alembic check` as `remove_table` --
    that is how the subscriptions table nearly acquired an autogenerated
    migration that would have dropped it.
    """
    __tablename__ = "outbox_events"
    __table_args__ = (
        Index("ix_outbox_events_partner_id", "partner_id"),
        # Partial index matching the dispatcher's claim query. Declared with the
        # same predicate as the DDL so autogenerate does not see a difference.
        Index("ix_outbox_events_claimable", "available_at",
              postgresql_where=text("status = 'pending'")),
        ForeignKeyConstraint(
            ["invitation_id", "partner_id"],
            ["invitations.id", "invitations.partner_id"],
            ondelete="CASCADE", name="fk_outbox_events_invitation_id_partner"),
        ForeignKeyConstraint(
            ["partner_id"], ["partners.id"], ondelete="CASCADE",
            name="fk_outbox_events_partner_id"),
        CheckConstraint("status IN ('pending', 'sent', 'failed')",
                        name="ck_outbox_events_status_enum"),
        CheckConstraint("attempts >= 0", name="ck_outbox_events_attempts_nonneg"),
        CheckConstraint(
            "(status = 'sent') = (token_ciphertext IS NULL AND sent_at IS NOT NULL)",
            name="ck_outbox_events_sent_has_no_secret"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), primary_key=True,
        server_default=text("gen_random_uuid()"))
    partner_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), nullable=False)
    invitation_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), nullable=False)
    event_type: Mapped[str] = mapped_column(String(50), nullable=False)
    recipient: Mapped[str] = mapped_column(String(320), nullable=False)

    # AEAD payload; nulled on delivery or dead-letter.
    token_ciphertext: Mapped[bytes | None] = mapped_column(LargeBinary, nullable=True)
    token_nonce: Mapped[bytes | None] = mapped_column(LargeBinary, nullable=True)
    key_version: Mapped[int] = mapped_column(Integer, nullable=False, server_default="1")

    status: Mapped[str] = mapped_column(String(20), nullable=False, server_default="pending")
    attempts: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    available_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()"))
    last_error: Mapped[str | None] = mapped_column(String(500), nullable=True)
    provider_message_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()"))
    sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
