import uuid
from datetime import datetime

from sqlalchemy import String, DateTime, ForeignKey, Index, func, text
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class Subscription(Base):
    """Direct-customer Stripe subscription, from the 0001 baseline.

    This table had no ORM model at all, so it was absent from Base.metadata and
    `alembic check` reported it as `remove_table` -- an autogenerated migration
    would have DROPPED the direct customers' billing rows. It is the most
    destructive item the metadata gate surfaced, and it predates every change in
    this series: the table was simply never modelled.

    It belongs to the platform/Stripe path only. 0008 revoked app_runtime's
    inherited DML on it, and it has no partner_id -- a subscription's tenant
    would have to be derived by joining users, which is why it is gated by role
    rather than by an RLS policy.
    """
    __tablename__ = "subscriptions"
    __table_args__ = (
        # Partial unique index from 0008: NULL means "not yet linked to Stripe",
        # and many rows may be unlinked, so uniqueness applies only to the
        # non-null values.
        Index("uq_subscriptions_stripe_id", "stripe_subscription_id",
              unique=True,
              postgresql_where=text("stripe_subscription_id IS NOT NULL")),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), primary_key=True,
        server_default=text("gen_random_uuid()"))
    user_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    stripe_customer_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    stripe_subscription_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    status: Mapped[str] = mapped_column(String(50), nullable=False, server_default="active")
    current_period_end: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False)
